export const environment = {
  production: false,
  apiUrl: 'https://cgbwebapi-001-site1.ptempurl.com',
  ckEditorLicenceKey: "eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NDQ2NzUxOTksImp0aSI6IjI2MjQxZjM0LTZjZjQtNDhjNC05MWJmLTk1MWY4MjE4M2I5YiIsInVzYWdlRW5kcG9pbnQiOiJodHRwczovL3Byb3h5LWV2ZW50LmNrZWRpdG9yLmNvbSIsImRpc3RyaWJ1dGlvbkNoYW5uZWwiOlsiY2xvdWQiLCJkcnVwYWwiLCJzaCJdLCJ3aGl0ZUxhYmVsIjp0cnVlLCJsaWNlbnNlVHlwZSI6InRyaWFsIiwiZmVhdHVyZXMiOlsiKiJdLCJ2YyI6ImY1NjVmYmRiIn0.yMKaKWMCmIx3UmCS2xVVxvcT3l1KDxjqWD9KyIt7ycRn11M74tAH0CgGswJ6HnPfRWOJQR0O2hjxGzPa1-OPEw"
};
